apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/imrightguy/CloudToLocalLLM/main/k8s/base/deployments/api-backend.yaml
  - https://raw.githubusercontent.com/imrightguy/CloudToLocalLLM/main/k8s/base/services/api-backend.yaml
  - https://raw.githubusercontent.com/imrightguy/CloudToLocalLLM/main/k8s/base/configmaps/main-config.yaml
