apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../deployments/postgres.yaml
  - ../services/postgres.yaml
  - ../postgres-auth-statefulset.yaml
  - ../configmaps/postgres-auth-init-scripts.yaml
