apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/api-backend
patches:
  - path: ../../../overlays/managed/env-patch.yaml
  - path: ../../../overlays/managed/scaling.yaml
