apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../deployments/app_base/api-backend
images:
  - name: imrightguycloudtolocalllm.azurecr.io/api-backend
    newTag: main-2b8cc66e773d97413c0e204ad79e340bc4c085f5-api-backend
patches:
  - path: ../../../deployments/overlays/managed/env-patch.yaml
  - path: ../../../deployments/overlays/managed/scaling.yaml
