apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../deployments/app_base/api-backend
images:
  - name: imrightguycloudtolocalllm.azurecr.io/api-backend
    newTag: main-1bf90126e50ed152eab193704119cc3efceca143-api-backend
patches:
  - path: ../../../deployments/overlays/managed/env-patch.yaml
  - path: ../../../deployments/overlays/managed/scaling.yaml
