apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/imrightguy/CloudToLocalLLM/k8s/base/utilities/blackbox-exporter.yaml?ref=main
  - https://github.com/imrightguy/CloudToLocalLLM/k8s/base/utilities/coturn.yaml?ref=main