apiVersion: apps/v1
kind: Deployment
metadata:
  name: builder
  namespace: cloudtolocalllm
  labels:
    app: builder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: builder
  template:
    metadata:
      labels:
        app: builder
    spec:
      imagePullSecrets:
        - name: regcred
      serviceAccountName: builder-sa
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: builder
          image: cloudtolocalllm/builder:latest
          imagePullPolicy: Always
          command: ["/bin/bash", "-c", "tail -f /dev/null"]
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1280Mi"
              cpu: "2000m"
          volumeMounts:
            - name: build-cache
              mountPath: /app
      volumes:
        - name: build-cache
          emptyDir: {}
