apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer-sa
  namespace: cloudtolocalllm
subjects:
  - kind: ServiceAccount
    name: deployer-sa
    namespace: cloudtolocalllm
roleRef:
  kind: ClusterRole
  name: deployer-role
  apiGroup: rbac.authorization.k8s.io
