apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apps/local/infrastructure
  - apps/local/postgres
  - apps/local/redis
  - apps/local/utilities
  - apps/local/api-backend
  - apps/local/web-frontend
  - apps/local/monitoring
  - apps/local/ingress-cloudflared
  - apps/local/ingress-local
