apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: monitoring:/Service:cloudtolocalllm/alertmanager
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"monitoring:/Service:cloudtolocalllm/alertmanager"},"labels":{"app":"alertmanager"},"name":"alertmanager","namespace":"cloudtolocalllm"},"spec":{"ports":[{"name":"http","port":9093,"targetPort":9093}],"selector":{"app":"alertmanager"},"type":"ClusterIP"}}
    creationTimestamp: "2025-12-24T23:56:26Z"
    labels:
      app: alertmanager
    name: alertmanager
    namespace: cloudtolocalllm
    resourceVersion: "8232554"
    uid: e7dafc0e-7cf7-49ea-80fc-b33417206054
  spec:
    clusterIP: 10.2.0.71
    clusterIPs:
    - 10.2.0.71
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 9093
      protocol: TCP
      targetPort: 9093
    selector:
      app: alertmanager
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: api-backend:/Service:cloudtolocalllm/api-backend
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"api-backend:/Service:cloudtolocalllm/api-backend"},"labels":{"app":"api-backend","environment":"development"},"name":"api-backend","namespace":"cloudtolocalllm"},"spec":{"ports":[{"name":"http","port":8080,"targetPort":8080}],"selector":{"app":"api-backend"},"type":"ClusterIP"}}
    creationTimestamp: "2025-12-24T23:56:35Z"
    labels:
      app: api-backend
      environment: development
    name: api-backend
    namespace: cloudtolocalllm
    resourceVersion: "8232856"
    uid: bd392946-992e-4522-ad05-f17e3440c671
  spec:
    clusterIP: 10.2.0.124
    clusterIPs:
    - 10.2.0.124
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: api-backend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: utilities:/Service:cloudtolocalllm/blackbox-exporter
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"utilities:/Service:cloudtolocalllm/blackbox-exporter"},"name":"blackbox-exporter","namespace":"cloudtolocalllm"},"spec":{"ports":[{"port":9115,"targetPort":9115}],"selector":{"app":"blackbox-exporter"}}}
    creationTimestamp: "2025-12-24T23:56:26Z"
    name: blackbox-exporter
    namespace: cloudtolocalllm
    resourceVersion: "8232530"
    uid: 108a6965-167f-44c3-92e6-e18144caa12f
  spec:
    clusterIP: 10.2.0.139
    clusterIPs:
    - 10.2.0.139
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 9115
      protocol: TCP
      targetPort: 9115
    selector:
      app: blackbox-exporter
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: utilities:/Service:cloudtolocalllm/coturn
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"utilities:/Service:cloudtolocalllm/coturn"},"name":"coturn","namespace":"cloudtolocalllm"},"spec":{"ports":[{"name":"turn-udp","port":3478,"protocol":"UDP","targetPort":3478},{"name":"turn-tcp","port":3478,"protocol":"TCP","targetPort":3478},{"name":"turn-tls","port":5349,"protocol":"TCP","targetPort":5349}],"selector":{"app":"coturn"},"type":"LoadBalancer"}}
    creationTimestamp: "2025-12-24T23:56:26Z"
    finalizers:
    - service.kubernetes.io/load-balancer-cleanup
    name: coturn
    namespace: cloudtolocalllm
    resourceVersion: "8232866"
    uid: 77011696-820c-4bb8-80bd-9e971aadee4a
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.2.0.118
    clusterIPs:
    - 10.2.0.118
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: turn-udp
      nodePort: 30955
      port: 3478
      protocol: UDP
      targetPort: 3478
    - name: turn-tcp
      nodePort: 30955
      port: 3478
      protocol: TCP
      targetPort: 3478
    - name: turn-tls
      nodePort: 32176
      port: 5349
      protocol: TCP
      targetPort: 5349
    selector:
      app: coturn
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 57.151.72.108
        ipMode: VIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: monitoring:/Service:cloudtolocalllm/grafana
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"monitoring:/Service:cloudtolocalllm/grafana"},"name":"grafana","namespace":"cloudtolocalllm"},"spec":{"ports":[{"name":"http","port":3000,"targetPort":3000}],"selector":{"app":"grafana"}}}
    creationTimestamp: "2025-12-24T23:56:26Z"
    name: grafana
    namespace: cloudtolocalllm
    resourceVersion: "8232560"
    uid: ec8f4ac6-4dee-42fb-a802-e03c4f6fe6a8
  spec:
    clusterIP: 10.2.0.72
    clusterIPs:
    - 10.2.0.72
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: grafana
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: postgres:/Service:cloudtolocalllm/postgres
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"postgres:/Service:cloudtolocalllm/postgres"},"labels":{"app":"postgres","environment":"development"},"name":"postgres","namespace":"cloudtolocalllm"},"spec":{"clusterIP":"None","ports":[{"name":"postgres","port":5432,"targetPort":5432}],"selector":{"app":"postgres"},"type":"ClusterIP"}}
    creationTimestamp: "2025-12-24T23:56:26Z"
    labels:
      app: postgres
      environment: development
    name: postgres
    namespace: cloudtolocalllm
    resourceVersion: "8232503"
    uid: 56a57eca-111f-4146-855e-908aef7b0c83
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: postgres
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: postgres:/Service:cloudtolocalllm/postgres-auth
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"postgres:/Service:cloudtolocalllm/postgres-auth"},"labels":{"app":"postgres-auth"},"name":"postgres-auth","namespace":"cloudtolocalllm"},"spec":{"ports":[{"name":"postgres","port":5432,"targetPort":5432}],"selector":{"app":"postgres-auth"},"type":"ClusterIP"}}
    creationTimestamp: "2025-12-24T23:56:26Z"
    labels:
      app: postgres-auth
    name: postgres-auth
    namespace: cloudtolocalllm
    resourceVersion: "8232510"
    uid: 06ab58ca-5f51-4f2e-b98c-226429358b06
  spec:
    clusterIP: 10.2.0.27
    clusterIPs:
    - 10.2.0.27
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: postgres-auth
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: monitoring:/Service:cloudtolocalllm/prometheus
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"monitoring:/Service:cloudtolocalllm/prometheus"},"name":"prometheus","namespace":"cloudtolocalllm"},"spec":{"ports":[{"port":9090,"targetPort":9090}],"selector":{"app":"prometheus"}}}
    creationTimestamp: "2025-12-24T23:56:26Z"
    name: prometheus
    namespace: cloudtolocalllm
    resourceVersion: "8232570"
    uid: 3f11fd2b-b51e-49f5-85c3-b2ab1b0f22f8
  spec:
    clusterIP: 10.2.0.42
    clusterIPs:
    - 10.2.0.42
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
    selector:
      app: prometheus
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: redis:/Service:cloudtolocalllm/redis-tunnel-state
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"redis:/Service:cloudtolocalllm/redis-tunnel-state"},"labels":{"app":"redis-tunnel-state"},"name":"redis-tunnel-state","namespace":"cloudtolocalllm"},"spec":{"clusterIP":"None","ports":[{"name":"redis","port":6379,"protocol":"TCP","targetPort":6379}],"selector":{"app":"redis-tunnel-state"},"type":"ClusterIP"}}
    creationTimestamp: "2025-12-24T23:56:26Z"
    labels:
      app: redis-tunnel-state
    name: redis-tunnel-state
    namespace: cloudtolocalllm
    resourceVersion: "8232498"
    uid: 12317181-cbf4-403e-b60f-65cfd4ed4f59
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      app: redis-tunnel-state
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: web-frontend:/Service:cloudtolocalllm/web
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"web-frontend:/Service:cloudtolocalllm/web"},"labels":{"app":"web","environment":"development"},"name":"web","namespace":"cloudtolocalllm"},"spec":{"ports":[{"name":"http","port":8080,"targetPort":8080}],"selector":{"app":"web"},"type":"ClusterIP"}}
    creationTimestamp: "2025-12-24T23:56:27Z"
    labels:
      app: web
      environment: development
    name: web
    namespace: cloudtolocalllm
    resourceVersion: "8232667"
    uid: 57a8e54d-9d1f-4580-ab51-6d9537b0ae2a
  spec:
    clusterIP: 10.2.0.37
    clusterIPs:
    - 10.2.0.37
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: web
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
