apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/deployments/api-backend.yaml
  - ../../base/services/api-backend.yaml
  - ../../base/configmaps/main-config.yaml