apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../deployments/overlays/managed/cloudflared-tunnel.yaml
patches:
  - path: ../../../deployments/overlays/managed/env-patch.yaml
