apiVersion: v1
kind: Service
metadata:
  name: streaming-proxy
  namespace: cloudtolocalllm
  annotations:
    cloud.google.com/backend-config: '{"default": "streaming-proxy-backendconfig"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: streaming-proxy
  ports:
  - port: 8080
    targetPort: 3001
