apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/imrightguy/CloudToLocalLLM/main/k8s/base/utilities/monitoring.yaml
  - https://raw.githubusercontent.com/imrightguy/CloudToLocalLLM/main/k8s/base/prometheus-config.yaml
  - https://raw.githubusercontent.com/imrightguy/CloudToLocalLLM/main/k8s/base/alertmanager-config.yaml
