apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/utilities
patches:
  - path: ../../../overlays/local/env-patch.yaml
  - path: ../../../overlays/local/resource-patch.yaml
