apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/imrightguy/CloudToLocalLLM/main/k8s/base/namespace.yaml
  - https://raw.githubusercontent.com/imrightguy/CloudToLocalLLM/main/k8s/base/rbac.yaml
  - https://raw.githubusercontent.com/imrightguy/CloudToLocalLLM/main/k8s/base/network-policies.yaml
