apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - network-policies.yaml
  - configmaps/main-config.yaml
  - configmaps/redis.yaml
  - services/redis.yaml
  - services/streaming-proxy.yaml
  - deployments/api-backend.yaml
  - deployments/web.yaml
  - deployments/postgres.yaml
  - deployments/redis.yaml
  - deployments/streaming-proxy.yaml
  - deployments/streaming-proxy-hpa.yaml
  - deployments/streaming-proxy-secret.yaml
  - configmaps/streaming-proxy-configmap.yaml
  - jobs/cloudflare-purge-job.yaml
  - alertmanager-config.yaml
  - prometheus-config.yaml
  - utilities/monitoring.yaml
  - utilities/blackbox-exporter.yaml
  - utilities/coturn.yaml
  - utilities/streaming-proxy-servicemonitor.yaml
  - postgres-auth-statefulset.yaml
