apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/deployments/postgres.yaml
  - ../../base/services/postgres.yaml
  - ../../base/postgres-auth-statefulset.yaml