apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudtolocalllm

resources:
  - ../../api-backend-deployment.yaml
  - ../../web-deployment.yaml
  - ../../configmap.yaml
  - ../../secrets.yaml

patches:
  - path: stripe-production-patch.yaml
    target:
      kind: Deployment
      name: api-backend
