apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/web-frontend
patches:
  - path: ../../../overlays/managed/env-patch.yaml
  - path: ../../../overlays/managed/scaling.yaml
