apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../deployments/app_base/web-frontend
images:
  - name: imrightguycloudtolocalllm.azurecr.io/web
    newTag: main-9e619f9a38a5ced1ff5291f13c64734e0c7a5d37
patches:
  - path: ../../../deployments/overlays/managed/env-patch.yaml
  - path: ../../../deployments/overlays/managed/scaling.yaml
