apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../deployments/app_base/web-frontend
images:
  - name: imrightguycloudtolocalllm.azurecr.io/web
    newTag: main-bc1a225bce8e303fcf9cf97fd8b6ff3fee7bddda
patches:
  - path: ../../../deployments/overlays/managed/env-patch.yaml
  - path: ../../../deployments/overlays/managed/scaling.yaml
