apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../deployments/app_base/web-frontend
images:
  - name: imrightguycloudtolocalllm.azurecr.io/web
    newTag: main-6e45e381ae8b2e406f3cc4f2305f19032e70fb81
patches:
  - path: ../../../deployments/overlays/managed/env-patch.yaml
  - path: ../../../deployments/overlays/managed/scaling.yaml
